"use client";
import Link from "next/link"; import { usePathname } from "next/navigation";
import { LayoutDashboard, Layers, FolderTree, ShoppingBag, Users, Settings, MessageSquare, ArrowLeft, Crown, CreditCard, Home } from "lucide-react";
export default function AdminSidebar(){ const pathname=usePathname();
  const links=[{name:"Dashboard",href:"/admin",icon:LayoutDashboard},{name:"Prompts",href:"/admin/prompts",icon:Layers},{name:"Categories",href:"/admin/categories",icon:FolderTree},{name:"Users",href:"/admin/users",icon:Users},{name:"Orders",href:"/admin/orders",icon:ShoppingBag},{name:"Payments",href:"/admin/payments",icon:CreditCard},{name:"Homepage",href:"/admin/homepage",icon:Home},{name:"VIP / Settings",href:"/admin/settings",icon:Crown},{name:"WhatsApp",href:"/admin/settings/whatsapp",icon:MessageSquare}];
  return <aside className="w-64 bg-[#080B11] border-r border-gray-800 hidden md:flex flex-col justify-between h-screen sticky top-0 shrink-0"><div className="p-6 space-y-6"><div className="flex items-center gap-2"><span className="text-xl font-black text-white">Prompt<span className="text-[#FF6B00]">Haat</span></span><span className="text-[10px] font-bold px-2 py-0.5 rounded bg-[#FF6B00]/20 text-[#FF6B00] border border-[#FF6B00]/30">ADMIN</span></div>
  <nav className="space-y-1.5">{links.map(item=>{ const Icon=item.icon; const active=pathname===item.href; return <Link key={item.href} href={item.href} className={`flex items-center gap-3 px-3.5 py-2.5 rounded-xl text-sm font-semibold ${active?"bg-[#FF6B00] text-white":"text-gray-400 hover:text-white hover:bg-[#151B28]"}`}><Icon className="w-4 h-4"/>{item.name}</Link> })}</nav></div>
  <div className="p-4 border-t border-gray-800"><Link href="/" className="flex items-center gap-2 px-3 py-2 text-xs font-semibold text-gray-400 hover:text-white"><ArrowLeft className="w-4 h-4"/> Exit to Main Site</Link></div></aside>;
}
